config/routes.rb
Rails.application.routes.draw do
	root 	 'static_pages#home'
  get  	 '/about',	 to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get  	 '/signup',  to: 'users#new'
  post 	 '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

	resources :users
	resources :events
  resources :event_attendings
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :event_attendings
	has_many :attendees, -> { where('invited == ?', true) }, through: :event_attendings, source: :event_attendee
	has_many :invited_guests, -> { where('invited == ?', false) }, through: :event_attendings, source: :event_attendee 
	belongs_to :creator, class_name: "User", foreign_key: "user_id"
	default_scope -> { order(created_at: :desc) }
	validates :creator, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  scope :upcoming_events, -> { where('event_date >= ?', Time.now) }
  scope :previous_events, -> { where('event_date <= ?', Time.now) }
  accepts_nested_attributes_for :event_attendings

end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
	belongs_to :event_attendee, :class_name => "User", foreign_key: "user_id", optional: true
  belongs_to :attended_event, :class_name => "Event", foreign_key: "event_id", optional: true
  accepts_nested_attributes_for :event_attendee, update_only: true

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
  has_many :event_attendings
  has_many :attended_events, through: :event_attendings, source: :attended_event
  has_many :events, foreign_key: "user_id", class_name: "Event", dependent: :destroy
	validates :name, presence: true
	validates :email, presence: true
  accepts_nested_attributes_for :attended_events

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
	def User.new_token
    	SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

   def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

private
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy]

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def index
    @events = Event.all
    @upcoming_events = Event.upcoming_events
    @past_events = Event.previous_events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new

  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Private event created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def update
  end

  def destroy
    @event.destroy
    flash[:success] = "Private event deleted"
    redirect_back(fallback_location: root_url)
  end

  private

    def event_params
      params.require(:event).permit(:title, :event_date, :description, { :invite_ids => [:user_id] })
    end

    def correct_user
      @event = current_user.events.find_by(id: params[:id])
      redirect_to root_url if @event.nil?
    end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user
      log_in @user
        params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
        redirect_back_or(@user)
    else
      flash[:danger] = 'Invalid email' 
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	  if logged_in?
    @event  = current_user.events.build
    #@attendee = User.find_by(params[:user_id])
    #@event_attendings = @event.event_attendings.build(user_id: @attendee.id)
    @event.save
      #@event  = current_user.events.build
      @feed_items = Event.all
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @created_upcoming_events = @user.events.upcoming_events
    @created_prev_events = @user.events.previous_events
    @attending_upcoming_events = @user.attended_events.upcoming_events
    @attending_prev_events = @user.attended_events.previous_events
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Welcome! It's time to make your first event."
      redirect_to root_url
    else
      render 'new'
    end
  end


    def user_params
      params.require(:user).permit(:name, :email)
    end  

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Private Events"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: cookies.signed[:user_id])
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Store the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/events/_event.html.erb
<li id="private event-<%= event.id %>">
  <span class="user"><%= link_to event.title, event %></span>
  <span class="content"> 
    Hosted by: <%= link_to event.creator.name, event.creator %>
    <% if event.event_date >= Time.now %>
      Happening in <%= distance_of_time_in_words(Time.now, event.event_date) %>
    <% else %> 
      Happened <%= distance_of_time_in_words(Time.now, event.event_date) %> ago.
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(event.created_at) %> ago.
    <% if current_user?(event.creator) %>
      <%= link_to "delete", event, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/events/index.html.erb
<% provide(:title, 'All Events') %>
<h1>All Events</h1>

<ul class="events">
	<h3>Upcoming Events</h3>
  <% @upcoming_events.each do |event| %>
    <li>
    	<%= link_to event.title, event %>
    </li>
	<% end %>
    <hr>
    <h3>Past Events</h3>
  <% @past_events.each do |event| %>
    <li>
    	<%= link_to event.title, event %>
    </li>
  <% end %>
</ul>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>
<div class="row">
  <div class="col-md-12">
    <div class="events">
      <h1>
        <%= @event.title %> -
          <% if @event.event_date >= Time.now %>
            Happening in <%= distance_of_time_in_words(Time.now, @event.event_date) %>
          <% else %> 
            Happened <%= distance_of_time_in_words(Time.now, @event.event_date) %> ago.
          <% end %> -
          Created by -<%= link_to @event.creator.name, @event.creator %>
      </h1><br>
      <h2>
          <% if current_user == @event.creator %>
              Send an invite:
              # NOTE TO SELF. ADD THE PEOPLE TO INVITE TO THE EVENT DURING THE EVENT CREATION STAGE INSTEAD OF HERE.
              <div class="event_form">
               <%= render 'shared/event_invite_form' %>
              </div>     
          <% elsif @event.invited_guests.include?(current_user) %>
              # show the invite
          <% else %>
              # "you must be invited to attend"
          <% end %>
      </h2>
      <hr>
      <% if @event.attendees.any? %>
      <h3>Event Attendees (<%= @event.attendees.count %>)</h3>
      <ol class="events">
        <%= render @event.attendees %>
      </ol>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    A Private Events App
    by <a href="http://www.deserthorsedesigns.com">Amy J</a>
  </small>
  <nav>
    <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><a href="http://www.theodinproject.com">A product thanks to - The Odin Project</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "#{current_user.name}'s", current_user, id:"loggedinuser" %> <%= link_to "private events", root_path, id: "logo" %> 
    <% else %>
      <%= link_to "private events", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
          <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title (yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container main-content">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_attend_event_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.text :title, placeholder: "Event name" %>
  	<%= f.datetime_select Date.today, prefix: :start_datetime %>
    <%= f.text_area :description, placeholder: "Start your new private event..." %> 
  </div>
  <%= f.submit "Create Event", class: "btn btn-primary" %>
<% end %>

app/views/shared/_attending_events.html.erb
  		<ol class="events">
        <h2>Upcoming Events:</h2>
        <% if @attending_upcoming_events %>
          <%= render @attending_upcoming_events %>
        <% else %>
          No current events found.
        <% end %>
			</ol>
      <ol class="events">
        <h2>Past Events:</h2>
        <% if @attending_prev_events %>
          <%= render @attending_prev_events %>
        <% else %>
          No past events found.
        <% end %>
      </ol>

app/views/shared/_created_events.html.erb
  		<ol class="events">
        <h2>Upcoming Events:</h2>
        <% if @created_upcoming_events %>
          <%= render @created_upcoming_events %>
        <% else %>
          No current events found.
        <% end %>
			</ol>
      <ol class="events">
        <h2>Past Events:</h2>
        <% if @created_prev_events %>
          <%= render @created_prev_events %>
        <% else %>
          No past events found.
        <% end %>
      </ol>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

app/views/shared/_event_form.html.erb
<%= form_for(@event) do |f| %>
  Create a new event:
  <div class="field">
  	<%= f.text_field :title, placeholder: "Event name" %>
  	<%= f.date_field :event_date, min: Date.today %>
    <%= f.text_area :description, placeholder: "Start your new private event..." %> 
    	And invite some guests to attend:
    <div class="field">
    	<%= f.fields_for (current_user.event_attendings.build) do |invite| %>
    		<%= invite.collection_select :user_id, User.all, :id, :name, {multiple: true} %>
    	<% end %>
    </div>
  </div>
  <%= f.submit "Create Event", class: "btn btn-primary" %>
<% end %>

app/views/shared/_event_invite_form.html.erb
<%= form_for(@invited) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.collection_select :user_id, User.all, :id, :name, {}, {multiple: true} %>
  </div>
  <%= f.submit "Invite", class: "btn btn-primary" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="events">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.events.count, "private event") %></span>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="event_form">
        <%= render 'shared/event_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Event Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="glass">
  <div class="jumbotron">
    <h1>Private Events</h1>
    <h2>
	   Start your very own private event.
    </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>
<% end %>

app/views/users/_user.html.erb
<li id="private event attendee-<%= user.id %>">
  <span class="user"><%= link_to user.name, user %></span>
  <span class="content"> 
    And they are so cool!
  </span>
  </span>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row pushdown">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
  	<% if @user.events.any? %>
  		<h3>Created Events (<%= @user.events.count %>)</h3>
    <%= render 'shared/created_events' %>
		<% end %>
    <hr>
    <% if @user.attended_events.any? %>
      <h3>Attending Events (<%= @user.attended_events.count %>)</h3>
        <%= render 'shared/attending_events' %>
    <% end %>
	</div>
</div>